function OperationEnums() {
  const Operations = {
    GETLEAVETYPE: 4,
    GETEMPLEAVES: 5,
    CREATELEAVE: 6,
    getPunchType: 1,
    getattendance: 8,
    writeswipe: 9,
    getempprofile: 10,
    getholidays: 11,
    getaccruals: 12,
    getleavesummary: 13,
    addteammember: 14,
    deleteteammember: 15,
    getemployees: 16,
    getteamleaves: 17,
    getteamattendance: 18,
    getmyteam: 19,
    requestPass: 20,
    getVisitingPass: 21,
    getAttendeesDetails: 22,
    updatetVisitingPass: 23,
    getNotifys: 24,
    updateleave: 25,
    createproject: 26,
    updateproject: 27,
    deleteproject: 28,
    getproject: 29,
    getProForEmp: 30,
    createprojectteam: 31,
    getprojectteam: 32,
    deleteprojectteam: 33,
    deletemilestone: 34,
    createmilestone: 35,
    updatemilestone: 36,
    getmilestone: 37,
    updatetask: 38,
    deletetask: 39,
    createtask: 40,
    gettask: 41,
    createtimesheet: 42,
    updatetimesheet: 43,
    deletetimesheet: 44,
    gettsbytask: 45,
    gettsbyuser: 46,
    deleteannouncemets: 47,
    createannouncemets: 48,
    updateannouncemets: 49,
    updateannouncemetisread: 50,
    getannouncemets: 51,
    createHolidays: 52,
    updateholiday: 53,
    deleteholiday: 54,
    createdept: 55,
    updatedeptt: 56,
    deletedept: 57,
    getdept: 58,
    getEmpByDept: 59,
    createEmp: 60,
    updateEmployee: 61,
    deleteEmployee: 62,
    getEmployee: 63,
    creRegBankDet: 64,
    updRegBankDet: 65,
    getRegBankDet: 66,
    delRegBankDet: 67,
    creRegProof: 68,
    upRegProof: 69,
    getRegProofs: 70,
    creRegDet: 71,
    upRegDet: 72,
    getRegDet: 73,
    creRegFamily: 74,
    updRegFamily: 75,
    RegFamily: 76,
    upManualAtd: 77,
    DayInOut: 78,
    DaySwipes: 79,
    createbranch: 100,
    updatebranch: 101,
    deletebranch: 102,
    getbranches: 103,
    getShiftsTypes: 104,
    assignshift: 105,
    getAsgsftEmp: 106,
    getEmpByShift: 107,
    resignEmp: 108,
    rejoinEmp: 109,
    Terminatedlist: 110,
    addmobileAccess: 111,
    adempprtalAces: 112,
    removemobAces: 113,
    rememppotalAces: 114,
    getReports: 80,
    getDayInOutDetailsEMPManager: 81,
    getreporthead: 82,
    creLeaveTypes: 83,
    upLeaveTypes: 84,
    delLeaveTypes: 85,
    getAttendancebystatus: 86,
    dashboard: 87,
    getaccuralsad: 88,
    getteamattforad: 89,
    getShiftCountByDate: 115,
    getAttendance7daysstatus: 116,
    uploadempFiles: 117,
    getempfilepaths: 118,
    getempfilesdelete: 119,
    createbomwithproductionorder: 200,
    addbomitem: 201,
    getbomdata: 202,
    updateBomItem: 203,
    deleteBomItem: 204,
    deleteBOM: 205,
    editBOM: 206,
    getBomItemAndProductionByQty: 207,
    getBOMinfo: 208,
    getBomIteminfo: 209,
    getAllBomItems: 210,
    getBomInfoById: 211,
    getcheckavailbulityitem: 212,
    getActiveBomCount: 213,
    getActiveBomItemCount: 214,
    uploadBOMFile: 215,
    getBomFilePathsByRefIdType: 216,
    searchbomnames: 217,
    searchbomitemnames: 218,
    insertCategory: 219,
    getAllCategories: 220,
    deleteCategory: 221,
    updateCategory: 222,
    createeducation: 223,
    updateeducation: 224,
    geteducationbyregid: 225,
    ismanager: 120,
    createbulkatt: 121,
    addqueuemail: 122,
    bulkemail: 123,
    UPbulkemail: 124,
    getRoles: 125,
    getModules: 126,
    getSubMenu: 127,
    salaryReport:418,
    regExpenses:401,
    getSalaryList:404,
    getpayrollcounts:410,
    getdepartmentwisesalariescount:412,
    getdpayrolloverviewcount:411,
    deleteAdvance:408,
    getPayRollProcessedStatus:415,
    ctcGet:1419,
    getSalaryAdvances:406,
    getPayPeriods:420,
    DepartmentWiseSalaries:421,
    getPayrollOverviewCount:422,
    getPayPeriod:423,
    PayrollImportedAttendance:424,
    PayrollProcessBranchWise:425
    ,GetEmployeePayReport:427,
    AddAdvancePayments:429,
    deleteAdvancePayments:430,
    getemployeespr:432,
    getRegExpensespr:433,
    addRegExpenses:434,
    ApproveRegExpenses:435,
    deleteRegExpenses:436,
    addVendorExp:437,
    getVendorExp:438,
    ApproveVendorExpenses : 439,
    deleteVendorExpenses : 440,
    ctcGetdetails:441,
    payslipsGet:426,
    UpdateEmpCtc:428,
    GetEmpCtcHistory:429,
    addEmpCtc:442,
    getSalaryGroupMaster:443,
    getNewEmpListForctcadd:444,
  };
  return Operations;
}

module.exports = {
  OperationEnums,
};
